"""empty message

Revision ID: 345dd2d1004a
Revises: 12b2e7444c90
Create Date: 2023-10-04 14:52:03.029037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345dd2d1004a'
down_revision = '12b2e7444c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_history',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_history')
    # ### end Alembic commands ###
