"""empty message

Revision ID: 89ceac6020fd
Revises: 8cb40ff64a03
Create Date: 2023-10-04 10:16:01.586553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ceac6020fd'
down_revision = '8cb40ff64a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('condition')
        batch_op.drop_column('category')
        batch_op.drop_column('description')
        batch_op.drop_column('size')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
