"""empty message

Revision ID: f5eb321930be
Revises: 89ceac6020fd
Create Date: 2023-10-04 10:23:01.872746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5eb321930be'
down_revision = '89ceac6020fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('category')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
