"""empty message

Revision ID: fa55d46ac746
Revises: c7210a436c13
Create Date: 2023-10-03 12:48:25.607790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa55d46ac746'
down_revision = 'c7210a436c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
